apiVersion: v1
kind: Service
metadata:
  name: nginx-my-service
spec:
  type: LoadBalancer # ClusterIP (default), NodePort, ExternalName, LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80